// examples/nuxtjs-v3/pages/index.vue
<template>
  <div>
    <!-- default theme -->
    <div class="p-10 bg-base-100 text-base-content">
      <button class="btn">button</button>
      <button class="btn btn-primary">button</button>
      <button class="btn btn-secondary">button</button>
      <button class="btn btn-accent">button</button>
    </div>

    <!-- garden theme -->
    <div class="p-10 bg-base-100 text-base-content" data-theme=garden>
      <button class="btn">button</button>
      <button class="btn btn-primary">button</button>
      <button class="btn btn-secondary">button</button>
      <button class="btn btn-accent">button</button>
    </div>

    <!-- forest theme -->
    <div class="p-10 bg-base-100 text-base-content" data-theme=forest>
      <button class="btn">button</button>
      <button class="btn btn-primary">button</button>
      <button class="btn btn-secondary">button</button>
      <button class="btn btn-accent">button</button>
    </div>
  </div>
</template>

// examples/nextjs/pages/index.jsx
import 'tailwindcss/tailwind.css'

export default function HomePage() {
  return (
    <>

      <div className="p-10 bg-base-100 text-base-content">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>

      <div className="p-10 bg-base-100 text-base-content" data-theme="garden">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>

      <div className="p-10 bg-base-100 text-base-content" data-theme="forest">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>

    </>
  );
}
