// src/docs2/src/components/homepage/Install.svelte
<div class="max-w-md min-h-screen mx-auto hero bg-base-100 text-base-content md:max-w-full"><div class="text-center hero-content"><div class="w-full max-w-md"><h2 class="mt-20 mb-2 text-4xl font-extrabold md:text-6xl">
  Install daisyUI
</h2> <p class="w-full max-w-lg mx-auto mt-5">
  No dependencies, pure CSS. Can be used as a Tailwind CSS plugin or as
  an independent CSS library
</p> <p class="w-full max-w-lg mx-auto mt-5 text-left">
  1. Install daisyUI as a Node package:
</p> <div class="w-full max-w-md mx-auto my-2"><div class="w-full max-w-xs mx-auto text-left shadow-lg mockup-code sm:max-w-none"><pre data-prefix="$"><code>npm i daisyui</code></pre></div> <p class="w-full max-w-lg mx-auto mt-5 text-left">
    2. Add daisyUI to Tailwind CSS as a plugin
  </p> <div class="w-full max-w-4xl my-2"><div class="w-full max-w-xs mx-auto text-sm text-left shadow-lg mockup-code sm:max-w-none"><pre><code><span class="text-neutral-content text-opacity-40">// tailwind.config.js</span>
  module.exports = {`{`}
    plugins: [
      <span class="badge badge-secondary">require('daisyui'),</span>
    ],
  {`}`}</code></pre></div></div> <a href="/docs/install" class="mt-4 mb-20 shadow-lg btn-wide btn-primary btn">
    Install guide
  </a></div></div></div></div>

// src/docs/pages/docs/install/index.vue
<template>
  <div>

    <TabHandler/>

    <h2 class="my-6 text-5xl font-bold">
      <span class="text-primary">Install as Tailwind CSS plugin</span>
    </h2>

    <Wrapper nocode>

      <p class="prose text-base-content opacity-60">
        You need
        <a target="_blank" href="https://nodejs.org/en/download/">Node.js</a> and
        <a target="_blank" href="https://tailwindcss.com/docs/installation">Tailwind CSS</a> installed.
      </p>

      <p class="my-4">
        1. Install DaisyUI:
      </p>
      <div class="w-full max-w-xl my-2">
        <div class="shadow-lg mockup-code">
          <pre data-prefix="$"><code>npm i daisyui --save</code></pre>
        </div>
      </div>

      <p class="my-4">
        2. Then add DaisyUI to your <span class="badge badge-outline">tailwind.config.js</span>
      </p>
      <div class="w-full max-w-xl my-2">
        <div class="text-sm shadow-lg mockup-code">
        <pre><code>module.exports = {

      plugins: [
        <span class="badge badge-primary">require('daisyui'),</span>
      ],

    }</code></pre>
        </div>
      </div>

    </Wrapper>


    <div class="flex justify-end max-w-4xl pt-10 mt-20 border-t-2 border-base-200">
      <NuxtLink to="/docs/use" class="text-xs btn-lg btn lg:text-lg">
        Next: How to use
        <Icon glyph="arrow" class="inline-block w-6 h-6 ml-2 stroke-current" />
      </NuxtLink>
    </div>


  </div>
</template>
<script>
export default {
  data() {
    return {
      DAISYUI_VERSION: process.env.DAISYUI_VERSION,
    }
  }
}
</script>
