// src/docs/pages/docs/install.vue
<template>
  <div>
    <h2 class="my-6 text-5xl font-bold">
      <span class="text-primary">Method 1: </span>
      <span>install with Node.js</span>
    </h2>
    <Wrapper nocode>

      <p class="prose text-base-content">
        You need
        <a target="_blank" href="https://nodejs.org/en/download/">Node.js</a> and
        <a target="_blank" href="https://tailwindcss.com/docs/installation">Tailwind CSS</a> installed.
      </p>

      <p class="my-4">
        1.Install DaisyUI:
      </p>
      <div class="w-full max-w-xl my-2">
        <div class="shadow-lg mockup-code">
          <pre data-prefix="$"><code>npm i daisyui --save</code></pre>
        </div>
      </div>

      <p class="my-4">
        2. Then add DaisyUI to your <span class="badge badge-outline">tailwind.config.js</span>
      </p>
      <div class="w-full max-w-xl my-2">
        <div class="text-sm shadow-lg mockup-code">
        <pre><code>module.exports = {

      plugins: [
        <span class="badge badge-primary">require('daisyui'),</span>
      ],

    }</code></pre>
        </div>
      </div>

<ul class="accordion accordion-arrow accordion-bordered mt-10 max-w-xl">
  <li class="accordion-item">
    <input id="windi-guide" type="checkbox">
    <label for="windi-guide" class="accordion-title">
      <Icon glyph="info" class="inline-block w-5 h-5 mr-2 stroke-current" />
      If you use WindiCSS, make these changes to
      <span class="badge badge-outline">tailwind.config.js</span>
  </label>
    <div class="accordion-body">
      <div class="w-full max-w-4xl my-2">
        <div class="text-sm shadow-lg mockup-code">
        <pre><code><span class="badge badge-primary">const { transform } = require('windicss/helpers')</span>

    module.exports = {

      plugins: [
        <span class="badge badge-primary">transform('daisyui'),</span>
      ],

      <span class="text-neutral-content text-opacity-40">// OPTIONAL: if you want to use DaisyUI colors everywhere</span>
      theme: {
        extend: {
          <span class="badge badge-primary">colors: require('daisyui/colors/windi'),</span>
        },
      },

    }</code></pre>
        </div>
      </div>
    </div>
  </li>
</ul>

      <h2 class="mt-20 text-5xl font-bold">
        <span class="text-primary">Method 2: </span>
        <span>Use CDN file</span>
      </h2>

      <p class="mt-4 prose text-base-content">
        You don't need to install anything. Just add the CSS file to your &lt;head&gt; tag.
        <br>However, these files are large for production and you can't purge unused styles.
      </p>

      <div class="w-full max-w-4xl my-2">
        <div class="text-sm shadow-lg mockup-code">
          <pre><code>
  <span class="text-neutral-content text-opacity-40">&lt;link href="</span>https://cdn.jsdelivr.net/npm/tailwindcss@2.1/dist/tailwind.min.css<span class="text-neutral-content text-opacity-40">" rel="stylesheet" type="text/css" /&gt;</span>
  <span class="text-neutral-content text-opacity-40">&lt;link href="</span>https://cdn.jsdelivr.net/npm/daisyui@{{ DAISYUI_VERSION }}/dist/full.css<span class="text-neutral-content text-opacity-40">" rel="stylesheet" type="text/css" /&gt;</span>

</code></pre>
        </div>
      </div>




    </Wrapper>


    <div class="flex justify-end max-w-4xl pt-10 mt-20 border-t-2 border-base-200">
      <NuxtLink to="/docs/use" class="text-xs btn-lg btn lg:text-lg">
        Next: How to use
        <Icon glyph="arrow" class="inline-block w-6 h-6 ml-2 stroke-current" />
      </NuxtLink>
    </div>


  </div>
</template>
<script>
export default {
  data() {
    return {
      DAISYUI_VERSION: process.env.DAISYUI_VERSION,
    }
  }
}
</script>

// src/docs/src/components/homepage/Install.svelte
<div class="hero bg-base-100 text-base-content mx-auto min-h-screen max-w-md md:max-w-full">
  <div class="hero-content text-center">
    <div class="w-full max-w-md">
      <h2 class="mt-20 mb-2 text-4xl font-extrabold md:text-6xl">Install daisyUI</h2>
      <p class="mx-auto mt-5 w-full max-w-lg">No dependencies, pure CSS. Can be used as a Tailwind CSS plugin or as an independent CSS library</p>
      <p class="mx-auto mt-5 w-full max-w-lg text-left">1. Install daisyUI as a Node package:</p>
      <div class="mx-auto my-2 w-full max-w-md">
        <div class="mockup-code mx-auto w-full max-w-xs text-left shadow-lg sm:max-w-none"><pre data-prefix="$"><code>npm i daisyui</code></pre></div>
        <p class="mx-auto mt-5 w-full max-w-lg text-left">2. Add daisyUI to Tailwind CSS as a plugin</p>
        <div class="my-2 w-full max-w-4xl">
          <div class="mockup-code mx-auto w-full max-w-xs text-left text-sm shadow-lg sm:max-w-none">
            <pre><code><span class="text-neutral-content text-opacity-40">// tailwind.config.js</span>
  module.exports = {`{`}
    plugins: [
      <span class="badge badge-secondary">require('daisyui'),</span>
    ],
  {`}`}</code></pre>
          </div>
        </div>
        <a href="/docs/install" class="btn-primary btn btn-wide mt-4 mb-20 shadow-lg">Install guide</a>
      </div>
    </div>
  </div>
</div>
