// examples/vue-vite/src/App.vue
<template>

  <!-- default theme (dark) -->
  <div class="p-10 bg-base-100 text-base-content">
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- garden theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=garden>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- forest theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=forest>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

</template>

// examples/svelte-rollup/src/App.svelte
<main>

  <!-- default theme (dark) -->
  <div class="p-10 bg-base-100 text-base-content">
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- garden theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=garden>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- forest theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=forest>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

</main>
