// examples/vue-vite/src/App.vue
<template>

  <!-- default theme (dark) -->
  <div class="p-10 bg-base-100 text-base-content">
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- garden theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=garden>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

  <!-- forest theme -->
  <div class="p-10 bg-base-100 text-base-content" data-theme=forest>
    <button class="btn">button</button>
    <button class="btn btn-primary">button</button>
    <button class="btn btn-secondary">button</button>
    <button class="btn btn-accent">button</button>
  </div>

</template>

// examples/react-webpack/src/app.js
import React from 'react';

const App = props => {
  return (
    <div>
      <div className="p-10 bg-base-100 text-base-content">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>

      <div className="p-10 bg-base-100 text-base-content" data-theme="garden">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>

      <div className="p-10 bg-base-100 text-base-content" data-theme="forest">
        <button className="btn">button</button>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <button className="btn btn-accent">button</button>
      </div>
    </div>
  );
}
export default App;
